### PR TITLE
Added initial support for setValue function

### PR DESCRIPTION
**Pull request by fidoboy**
Tested and working on Android. Can't test it already on iOS but it should work... I hope

### CODE REVIEW

**Comment by pentateu** [comment]
We have added the setValue method to the plugin and we have also fixed some issues on iOS where the panel was not positioning properly, which perhaps is the same thing you were trying todo with your changes in iOS.

**Comment by fidoboy** [comment]
Great!! I'll try it as soon as possible. I was unable to fix the positioning problems in both iOS 7 and 8. You will need also to add an option to pan the main view to the top when keyboard is being displayed. That way, the items at bottom of screen remains visible when keyboard is opened...

**Comment by fidoboy** [comment]
Still not working as expected. The show method now opens the keyboard and also both buttons are now aligned to the left. When input looses the focus, the panel disappears

**Comment by fidoboy** [comment]
Your changes on Android are missing my fixes for image buttons. Right now, your fork is not working with image icons. setValue added into my fork is still missing in yours. Please, use my fork as starting point cause it solves more things than your, but still there is issues with iOS positioning

**Pull request closed without merging**
